__all__ = ('NavigationPlugin',)

from typing import Mapping, Type
import abc

import attr
from loguru import logger
from roswire.name import namespace_join

from ...interpreter import Interpreter, ModelPlugin
class NavigationPlugin(ModelPlugin):
    # e.g., {name: static_map, type: "costmap_2d::StaticLayer"}
    @classmethod
    def from_dict(cls, dict_: Mapping[str,str]) -> 'NavigationPlugin':
        cpp_class = dict_['type']
        name = dict_['name']
        logger.debug(f'loading navigation plugin [{name}] from file [{cpp_class}]')
        cpp_to_cls: Mapping[str, Type[NavigationPlugin]] = {
            'costmap_2d::StaticLayer': StaticLayerPlugin,
            'costmap_2d::FetchDepthLayer': FetchDepthLayerPlugin,
            'costmap_2d::InflationLayer': InflationLayerPlugin,
            'costmap_2d::ObstacleLayer': ObstacleLayerPlugin
        }

        cls = cpp_to_cls[cpp_class]
        plugin = cls.build(name)
        logger.debug(f'loaded navigation plugin [{name}] from file [{cpp_class}]: {plugin}')
        return plugin

    @classmethod
    @abc.abstracmethod
    def build(cls, name: str) -> 'NavigationPlugin':
        ...

@attr.s(frozen=True, slots=True)
class StaticLayerPlugin(NavigationPlugin):
    """
    The static map layer represents a largely unchanging portion of the costmap, like those generated by SLAM.

    http://wiki.ros.org/costmap_2d/hydro/staticmap
    """
    class_name = 'costmap_2d::StaticLayer'

    def load(self, interpreter: Interpreter) -> None:
        move_base = interpreter.nodes['/move_base'] # TODO: could be renamed by launch?

        move_base.read('unknown_cost_value', -1)
        move_base.read('lethal_cost_value', 100)
        map_topic = move_base.read('map_topic', '/map')
        move_base.read('first_map_only', False)
        subscribe_to_updates = move_base.read('subscribe_to_updates', False)
        move_base.read('track_unknown_space', True)
        move_base.read('use_maximum', False)
        move_base.read('trinary_costmap', True)

        move_base.sub(map_topic, 'nav_msgs/OccupancyGrid')
        if subscribe_to_updates:
            move_base.sub(f'{map_topic}_updates', )

    @classmethod
    def build(cls) -> NavigationPlugin:
        return StaticLayerPlugin()


@attr.s(frozen=True, slots=True)
class InflationLayerPlugin(NavigationPlugin):
    """
    The inflation layer is an optimization that adds new values around lethal obstacles (i.e. inflates the obstacles)
    in order to make the costmap represent the configuration space of the robot.

    http://wiki.ros.org/costmap_2d/hydro/inflation
    """
    class_name = 'costmap_2d::InflationLayer'

    def load(self, interpreter: 'Interpreter') -> None:
        move_base = interpreter.nodes['/move_base']
        move_base.read('~/inflation_radius', 0.55)
        move_base.read('~/cost_scaling_factor', 10.0)

    @classmethod
    def build(cls) -> NavigationPlugin:
        return InflationLayerPlugin()

@attr.s(frozen=True, slots=True)
class FetchDepthLayerPlugin(NavigationPlugin):
    """
    TODO: This should really be generated

    from /ros_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp of the Fetch container from TheRobotCooperative
    """
    class_name = 'costmap_2d::FetchDepthLayer'

    def load(self, interpreter: 'Interpreter') -> None:
        mb = interpreter.nodes['/move_base']

        publish_observations=mb.read('publish_observations', False)
        mb.read('observations_separation_threshold', 0.06)
        mb.read('find_ground_plane', True)
        mb.read('ground_orientation_threshold', 0.9)
        mb.read('min_obstacle_height', 0.0)
        mb.read('max_obstacle_height', 2.0)
        mb.read('min_clearing_height', float('inf'))
        mb.read('max_clearing_height', float('inf'))
        mb.read('skip_rays_bottom', 20)
        mb.read('skip_rays_top', 20)
        mb.read('skip_rays_left', 20)
        mb.read('skip_rays_right', 20)
        mb.read('clear_with_skipped_rays', False)
        mb.read('observation_persistence', 0.0)
        mb.read('expected_update_rate', 0.0)
        mb.read('transform_tolerance', 0.5)
        mb.read('obstacle_range', None) #TODO is this the right way to handle this?
        mb.read('raytrace_range', None)

        if publish_observations:
            mb.pub('clearing_obs', 'sensor_msgs/PointCloud')
            mb.pub('marking_obs', 'sensor_msgs/PointCloud')

        depth_topic = mb.read('depth_topic', '/head_camera/depth_downsample/image_raw')
        info_topic = mb.read('info_topic', "/head_camera/depth_downsample/camera_info")

        mb.sub(depth_topic, 'sensor_msgs/Image')
        mb.sub(info_topic, 'sensor_msgs/CameraInfo')

    @classmethod
    def build(cls, name: str) -> 'NavigationPlugin':
        return FetchDepthLayerPlugin()

@attr.s(frozen=True, slots=True)
class ObstacleLayerPlugin(NavigationPlugin):
    """
    The obstacle layer tracks the obstacles as read by the sensor data. The ObstacleCostmapPlugin marks and raytraces
    obstacles in two dimensions, while the VoxelCostmapPlugin does so in three dimensions.

    http://wiki.ros.org/costmap_2d/hydro/obstacles
    """
    class_name = 'costmap_2d::ObstacleLayer'

    def load(self, interpreter: 'Interpreter') -> None:
        mb = interpreter.nodes['/move_base']

        observation_sources_param = namespace_join(mb.name, namespace_join('obstacles', 'observation_sources'))
        observation_sources = mb.read(observation_sources_param, "")

        for os in observation_sources.split(" "):
            os_ns = namespace_join(mb.name, namespace_join('obstacles', os))
            topic = mb.read(namespace_join(os_ns, 'topic'), os)
            mb.read(namespace_join(os_ns, 'sensor_frame'), "")
            mb.read(namespace_join(os_ns, 'observation_persistence'), 0.0)
            mb.read(namespace_join(os_ns, 'expected_update_rate'), 0.0)
            data_type = mb.read(namespace_join(os_ns, 'data_type'), "PointCloud")
            mb.read(namespace_join(os_ns, 'min_obstacle_height'), 0.0)
            mb.read(namespace_join(os_ns, 'max_obstacle_height'), 2.0)
            mb.read(namespace_join(os_ns, 'inf_is_valid'), False)
            mb.read(namespace_join(os_ns, 'clearing'), False)
            mb.read(namespace_join(os_ns, 'marking'), True)

            assert data_type in ['PointCloud', 'LaserScan', 'PointCloud2']

            if data_type == 'LaserScan':
                mb.sub(topic, "sensor_msgs/LaserScan")
            elif data_type == 'PointCloud2':
                mb.sub(topic, 'sensor_msgs/PointCloud2')
            elif data_type == 'PointCloud':
                mb.sub(topic, 'sensor_msgs/PointCloud')

    @classmethod
    def build(cls, name: str) -> 'NavigationPlugin':
        return ObstacleLayerPlugin()
