FROM autoware/autoware:1.10.0-kinetic-cuda

ENV DEBIAN_FRONTEND noninteractive

RUN sudo apt-get update \
 && sudo apt-get install -y build-essential checkinstall\
 && sudo apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev\
 && cd /usr/src \
 && sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz \
 && sudo tar xzf Python-2.7.18.tgz \
 && cd Python-2.7.18 \
 && sudo ./configure --enable-optimizations \
 && sudo make altinstall \
 && sudo apt update \
 && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | sudo python2.7 \
 && python2.7 -m pip install -U wstools 

RUN sudo apt-get update \
 && sudo apt-get install -y --no-install-recommends \
      apt-utils \
      bzip2 \
      cmake \
      clang \
      build-essential \
      ca-certificates \
      curl \
      gcc \
      g++ \
      mercurial \
      python-pip \
      "ros-kinetic-cmake-modules" \
      software-properties-common \
      tmux \
      vim \
      wget 

# install vncserver
RUN sudo apt-get update \
 && sudo apt-get install -y \
      dialog \
      apt-utils \
      supervisor \
      vnc4server \
      xfce4 \
      xfce4-goodies \
      xfce4-terminal \
      xserver-xorg-core \
      xterm \
      xvfb \
      x11vnc \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/* \
 && sudo mkdir ~/.vnc \
 && sudo /bin/bash -c "echo -e 'r0sD!sc0ver\nr0sD!sc0ver\nn' | vncpasswd"
ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /bin/tini
RUN sudo chmod +x /bin/tini

 RUN sudo apt-get clean \
 && sudo apt-get update && sudo apt-get upgrade -y --force-yes \
 && sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list' \
 && sudo wget http://packages.ros.org/ros.key -O - | sudo apt-key add - \
 && sudo apt-get update \
 && sudo apt-get install python-rosinstall -y --force-yes \
 && python2.7 -m pip install \
      catkin-tools==0.4.5 \
      coverage==5.1 \
      rosinstall-generator==0.1.18 \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && sudo apt-get update \
&& sudo apt-get install -y python-coverage \
 python-catkin-pkg \
 python-rosdep \
 python-rosdistro \
 python-rosinstall \
 python-rosinstall-generator \
 python-rospkg \
 python-vcstools \
 python-wstool \ 
 ros-kinetic-automotive-platform-msgs \
 libproj-dev

RUN curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash 
RUN exec $SHELL \
&& export PYENV_ROOT="$HOME/.pyenv" \
&& export PATH="$PYENV_ROOT/bin:$PATH" \
&& eval "$(pyenv init --path)" \
&& eval "$(pyenv init -)" \
&& eval "$(pyenv virtualenv-init -)" \
&& pyenv install 2.7.18 \
&& pyenv global 2.7.18 \
&& sudo -H pip install setuptools
      
ARG DIRECTORY
COPY "${DIRECTORY}" /install/

RUN sudo wstool init -j8 src_pre_bug /install/pre_bug.rosinstall \
&& rosdep update \
&& rosdep install -i -y -r --from-paths src_pre_bug \
      --ignore-src \
      --skip-keys="python-rosdep python-catkin-pkg python-rospkg" \
      --rosdistro="kinetic" \
&& sudo chmod o+r+w+x -R /src_pre_bug \
&& sudo wstool init -j8 src_bug /install/bug.rosinstall \
&& rosdep install -i -y -r --from-paths src_bug \
      --ignore-src \
      --skip-keys="python-rosdep python-catkin-pkg python-rospkg" \
      --rosdistro="kinetic" \
&& sudo chmod o+r+w+x -R /src_bug \ 
&& sudo wstool init -j8 src_bug_fix /install/bug_fix.rosinstall \
&& rosdep install -i -y -r --from-paths src_bug_fix \
      --ignore-src \
      --skip-keys="python-rosdep python-catkin-pkg python-rospkg" \
      --rosdistro="kinetic"  \
&& sudo chmod o+r+w+x -R /src_bug_fix

COPY ../rootfs /

RUN source /opt/ros/indigo/setup.sh \
 && /src_pre_bug/repo/ros/catkin_make_release \
 && /src_bug/repo/ros/catkin_make_release \
 && /src_bug_fix/repo/ros/catkin_make_release 
