all = autoware-01 autoware-02 autoware-03 autoware-04 autoware-05

autoware-01:
	python analysis.py bugs/autoware-01/bug.yml Dockerfile-i
autoware-02:
	python analysis.py bugs/autoware-02/bug.yml Dockerfile-i
autoware-03:
	python analysis.py bugs/autoware-03/bug.yml Dockerfile-i
autoware-04:
	python analysis.py bugs/autoware-04/bug.yml Dockerfile-k
autoware-05:
	python analysis.py bugs/autoware-05/bug.yml Dockerfile-k
